author: "Alexandru Coman"
title: "PrettyDocs Jekyll"
meta:
header:
  title: 'Pretty'
  subtitle: 'Docs'
  icon: 'fas fa-book'
  tagline: []
social:
  - title: "Github Page"
    icon: "fab fa-github"
    url: ""
  - title: "LinkedIn Profile"
    icon: "fab fa-linkedin"
    url: ""
  - title: "Facebook Page"
    icon: "fab fa-facebook"
    url: ""
  - title: "RSS Feed"
    icon: "fas fa-rss"
    url: ""
