author: "Alexandru Coman"
title: "PrettyDocs Jekyll"
meta:
header:
  title: 'Pretty'
  subtitle: 'Docs'
  tagline: []
social:
  - title: "github"
    url: ""
  - title: "linkedin"
    url: ""
  - title: "facebook"
    url: ""
  - title: "twitter"
    url: ""
  - title: "youtube"
    url: ""
  - title: "link"
    url: ""
  - title: "rss"
    url: ""
